name: Build and Push Docker Image
 
on:
  repository_dispatch:
    types: [build-and-push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ inputs.docker_password }}" | docker login -u "${{ inputs.docker_username }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ inputs.repo_name }}/${{ inputs.image_name }}:${{ github.sha }} .
          docker push ${{ inputs.repo_name }}/${{ inputs.image_name }}:${{ github.sha }}
