name: Deploy to EC2 with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Pull the latest image
        run: docker pull mishikabatra/my-image:latest

      - name: Tag the image with a new tag
        id: tag_image
        run: |
          SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-5)
          NEW_TAG=${SHA_SHORT}-${{ github.run_number }}
          docker tag mishikabatra/my-image:latest mishikabatra/my-image:${NEW_TAG}
          docker push mishikabatra/my-image:${NEW_TAG}
          echo "::set-output name=image_tag::${NEW_TAG}"

      - name: Deploy to EC2
        env:
          AWS_EC2_HOST: ${{ secrets.EC2_HOST }}
          AWS_EC2_USER: ${{ secrets.EC2_USER }}
          AWS_EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
          IMAGE_TAG: ${{ steps.tag_image.outputs.image_tag }}
        run: |
          echo "$AWS_EC2_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem
          scp -o StrictHostKeyChecking=no -i ec2_key.pem docker-compose.yml $AWS_EC2_USER@$AWS_EC2_HOST:~/docker-compose.yml
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $AWS_EC2_USER@$AWS_EC2_HOST << EOF
            sudo docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
            sed -i "s/latest/$IMAGE_TAG/" ~/docker-compose.yml
            sudo docker-compose -f ~/docker-compose.yml pull
            sudo docker-compose -f ~/docker-compose.yml down
            sudo docker-compose -f ~/docker-compose.yml up -d
          EOF
