name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build and push to Docker Hub
        env:
          BRANCH: production
          REPO_NAME: mishikabatra
          IMAGE_NAME: production_image
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build_image.yml/dispatches \
            -d '{"ref":"production", "inputs": {"branch": "production", "repo_name": "mishikabatra", "image_name": "production_image", "docker_username": "${DOCKER_USERNAME}", "docker_password": "${DOCKER_PASSWORD}"}}'
