name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build and push
        uses: actions/github-script@v4
        with:
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build_image.yml',
              ref: 'production',
              inputs: {
                branch: 'production',
                repo_name: 'mishikabatra',
                image_name: 'my-production-image'
              }
            })
