name: Deploy to stage

on:
  push:
    branches:
      - staging

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    env:
      REPO_BASE_NAME : mishikabatra
      REPO_NAME: stage
      BUILD_FOR_PRODUCTION: "/.github/workflows/build_image.yml"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
