name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build and push to Docker Hub
        env:
          BRANCH: staging
          REPO_NAME: mishikabatra
          IMAGE_NAME: stage-image
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build_image.yml/dispatches \
            -d '{"ref":"staging", "inputs": {"branch": "staging", "repo_name": "mishikabatra", "image_name": "stage_image", "docker_username": "${DOCKER_USERNAME}", "docker_password": "${DOCKER_PASSWORD}"}}'
